[Chore]: update github action

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -31,12 +31,12 @@ jobs:
 
       # 4. Gradle로 빌드
       - name: Build with Gradle
-        run: ./gradlew build
+        run: ./gradlew build || (echo "Gradle build failed!" && exit 1)
 
       # 5. JAR 파일 EC2로 복사
       - name: Upload JAR to EC2
         run: |
-          scp -i ${{ secrets.EC2_PRIVATE_KEY }} ./build/libs/stay-with-me.jar ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/apps/stay-with-me/stay-with-me.jar
+          scp -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ github.workspace }}/build/libs/stay-with-me.jar ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/apps/stay-with-me/stay-with-me.jar
 
       # 6. EC2에서 애플리케이션 실행
       - name: SSH into EC2 and run the app
