[Chore]: update github action

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -65,24 +65,24 @@ jobs:
       # 8. EC2에서 애플리케이션 실행
       - name: SSH into EC2 and run the app
         run: |
-          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << "EOF"
-            # 실행 중인 프로세스 종료
-            PID=\$(pgrep -f 'stay-with-me.jar')
-            if [ ! -z "\$PID" ]; then
-              echo "Stopping existing application (PID: \$PID)"
-              kill -9 \$PID
-            fi
-
-            # JAR 실행 (백그라운드 실행)
-            nohup java -jar /apps/stay-with-me/stay-with-me.jar > /apps/stay-with-me/app.log 2>&1 &
-
-            # 실행 확인 (10초 대기 후 프로세스 체크)
-            sleep 10
-            NEW_PID=\$(pgrep -f 'stay-with-me.jar')
-            if [ -z "\$NEW_PID" ]; then
-              echo "Error: Application failed to start!"
-              exit 1
-            fi
-
-            echo "Application deployed and running (PID: \$NEW_PID)."
+          ssh -T -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << "EOF"
+          # 실행 중인 프로세스 종료
+          PID=\$(pgrep -f 'stay-with-me.jar')
+          if [ ! -z "\$PID" ]; then
+          echo "Stopping existing application (PID: \$PID)"
+          kill -9 \$PID
+          fi
+          
+          # JAR 실행 (백그라운드 실행)
+          nohup java -jar /apps/stay-with-me/stay-with-me.jar > /apps/stay-with-me/app.log 2>&1 &
+          
+          # 실행 확인 (10초 대기 후 프로세스 체크)
+          sleep 10
+          NEW_PID=\$(pgrep -f 'stay-with-me.jar')
+          if [ -z "\$NEW_PID" ]; then
+          echo "Error: Application failed to start!"
+          exit 1
+          fi
+          
+          echo "Application deployed and running (PID: \$NEW_PID)."
           EOF
